'use server';

/**
 * @fileOverview Generates an initial draft of marketing content based on user input.
 *
 * - generateInitialDraft - A function that generates the initial draft.
 * - GenerateInitialDraftInput - The input type for the generateInitialDraft function.
 * - GenerateInitialDraftOutput - The return type for the generateInitialDraft function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateInitialDraftInputSchema = z.object({
  industry: z.string().describe('The industry of the content.'),
  targetAudience: z.string().describe('The target audience for the content.'),
  desiredMessage: z.string().describe('The desired message to convey in the content.'),
  contentType: z.string().describe('The type of content to generate (e.g., blog post, social media update).'),
});
export type GenerateInitialDraftInput = z.infer<typeof GenerateInitialDraftInputSchema>;

const GenerateInitialDraftOutputSchema = z.object({
  draftContent: z.string().describe('The initial draft content generated by the AI.'),
});
export type GenerateInitialDraftOutput = z.infer<typeof GenerateInitialDraftOutputSchema>;

export async function generateInitialDraft(input: GenerateInitialDraftInput): Promise<GenerateInitialDraftOutput> {
  return generateInitialDraftFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateInitialDraftPrompt',
  input: {schema: GenerateInitialDraftInputSchema},
  output: {schema: GenerateInitialDraftOutputSchema},
  prompt: `You are an AI assistant specialized in generating marketing content.

  Based on the provided information, generate an initial draft for the requested content type.

  Industry: {{{industry}}}
  Target Audience: {{{targetAudience}}}
  Desired Message: {{{desiredMessage}}}
  Content Type: {{{contentType}}}

  Draft Content:`, 
});

const generateInitialDraftFlow = ai.defineFlow(
  {
    name: 'generateInitialDraftFlow',
    inputSchema: GenerateInitialDraftInputSchema,
    outputSchema: GenerateInitialDraftOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
